### ISSUE TITLE
Test Suite Fails on Windows w/ Sqlite 3.12

### ISSUE THREAD

**Issue by ebrown** [rogerbinns/apsw#215] opened 2016-04-04 21:29 UTC
Visual Studio 2015 sp1
Python 3.5.1

python setup.py fetch --all --missing-checksum-ok build install test

At the end of the test python keeps mallocing memory until all system memory is consumed. 

e89278e67609b3eba3708b3804192728a2d4d59b

**Comment by rogerbinns** [comment] 2016-04-05 01:36
Thanks for the report.  This is a known problem I am still working on, which is why there hasn't been APSW 3.12 release.  Note that the tests work perfectly with SQLite 3.11 and just changing the SQLite version is enough to see the problem.  So far I have tracked it down to something in the VFS tests, but still haven't found the cause.  Sadly various tools and debugging techniques completely change what is happening (and they really shouldn't).  I am closing this not because it isn't an issue, but because this is already part of the work for the new SQLite 3.12 release.

**Closed by rogerbinns** 2016-04-05 01:36 UTC
