### ISSUE TITLE
VFS Null filename opens

### ISSUE THREAD

**Issue by abdelouahabb** [rogerbinns/apsw#506] opened 2024-01-05 16:13 UTC
I try to retrieve data using `SELECT something from product LIMIT ?,?` from an obfuscated db, with 500 pagination skip, the problem I get an error when I reach 5500 (skip=6000) : 
Is there any limit should be raised for the cursor ?

The error : 

          
```
Traceback (most recent call last):
  File "C:\Users\abdelouahab\AppData\Local\Programs\Python\Python311\Lib\site-packages\tornado\web.py", line 1790, in _execute
    result = await result
             ^^^^^^^^^^^^
  File "c:\Users\abdelouahab\Desktop\stocks\application\app.py", line 1005, in get
    cur.execute('''
  File "c:\Users\abdelouahab\Desktop\stocks\application\app.py", line 55, in xOpen
    return ObfuscatedVFSFile(self.base_vfs, name, flags)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\abdelouahab\Desktop\stocks\application\app.py", line 61, in __init__
    apsw.VFSFile.__init__(self, inheritfromvfsname, filename, flags)
TypeError: filename should be a string
```

```
Windows 10 64bits,
APSW 3.44.2.0,
Python Python 3.11.7
```

**Comment by rogerbinns** [comment] 2024-01-05 16:53
APSW doesn't change SQLite's behaviour when it comes to executing SQL.

> TypeError: filename should be a string

That is the error you are getting.  You should print out what the value of filename actually is, as well as the flags.  [augmented tracebacks](https://rogerbinns.github.io/apsw/ext.html#apsw.ext.print_augmented_traceback) will also contain the same information.  My guess is SQLite is spilling from memory to disk.

If you want further help you'll need to include the APSW version, as well as enough for me to reproduce the problem.

**Comment by abdelouahabb** [comment] 2024-01-05 17:19
> APSW doesn't change SQLite's behaviour when it comes to executing SQL.
> 
> > TypeError: filename should be a string
> 
> That is the error you are getting. You should print out what the value of filename actually is, as well as the flags. [augmented tracebacks](https://rogerbinns.github.io/apsw/ext.html#apsw.ext.print_augmented_traceback) will also contain the same information. My guess is SQLite is spilling from memory to disk.
> 
> If you want further help you'll need to include the APSW version, as well as enough for me to reproduce the problem.

Sorry, here is what I got : 

 ```
 File "c:\Users\abdelouahab\Desktop\stocks\application\app.py", line 1008, in get
    cur.execute('''
    contenu = 'Année Passée'
    exc = TypeError('filename should be a string')
    fin = 500
    nombre = (8099,)
    now = datetime.datetime(2024, 1, 5, 18, 16, 43, 611, tzinfo=zoneinfo.ZoneInfo(key='Africa/Algiers'))
    pagination = 16
    self = <__main__.Recette object at 0x000001EB7FED2390>
    start = 6000
    url = '/admin/recette?q=l'
    what = 'l&skip'

  File "c:\Users\abdelouahab\Desktop\stocks\application\app.py", line 57, in xOpen
    return ObfuscatedVFSFile(self.base_vfs, name, flags)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    flags = [1054, 0]
    name = None
    self = <__main__.ObfuscatedVFS object at 0x000001EB7F8932A0>

  File "c:\Users\abdelouahab\Desktop\stocks\application\app.py", line 63, in __init__
    apsw.VFSFile.__init__(self, inheritfromvfsname, filename, flags)
    filename = None
    flags = [1054, 0]
    inheritfromvfsname = ''
    self = <__main__.ObfuscatedVFSFile object at 0x000001EB104A7F70>
```

TypeError: filename should be a string

**Comment by rogerbinns** [comment] 2024-01-05 22:57
This is a bug in APSW.  

The open flags are `SQLITE_OPEN_CREATE |
SQLITE_OPEN_DELETEONCLOSE |
SQLITE_OPEN_EXCLUSIVE |
SQLITE_OPEN_READWRITE |
SQLITE_OPEN_TRANSIENT_DB`

The SQLite doc does say [NULL is allowed](https://sqlite.org/c3ref/vfs.html#:~:text=SQLite%20guarantees%20that%20the%20zFilename%20parameter%20to%20xOpen%20is%20either%20a%20NULL%20pointer).  I vaguely recall in the past that a zero length string was passed.

This exact combination only occurs for `OP_OpenAutoindex` /  `OP_OpenEphemeral` in [the source](https://sqlite.org/src/file?name=src/vdbe.c&ci=trunk#:~:text=case%20OP_OpenAutoindex%3A%20%20%20%20%20%20%20/*%20ncycle%20*/%0Acase%20OP_OpenEphemeral%3A%20%7B%20%20%20%20%20/*%20ncycle%20*/)

The reason you are hitting this is because as you add larger offsets to your `LIMIT` , more data has to be kept in memory to be sorted until memory limits are hit and disk is used instead.

Once I have a reproducer I'll let you know of a workaround.

**Comment by abdelouahabb** [comment] 2024-01-06 12:16
> This is a bug in APSW.
> 
> The open flags are `SQLITE_OPEN_CREATE | SQLITE_OPEN_DELETEONCLOSE | SQLITE_OPEN_EXCLUSIVE | SQLITE_OPEN_READWRITE | SQLITE_OPEN_TRANSIENT_DB`
> 
> The SQLite doc does say [NULL is allowed](https://sqlite.org/c3ref/vfs.html#:~:text=SQLite%20guarantees%20that%20the%20zFilename%20parameter%20to%20xOpen%20is%20either%20a%20NULL%20pointer). I vaguely recall in the past that a zero length string was passed.
> 
> This exact combination only occurs for `OP_OpenAutoindex` / `OP_OpenEphemeral` in [the source](https://sqlite.org/src/file?name=src/vdbe.c&ci=trunk#:~:text=case%20OP_OpenAutoindex%3A%20%20%20%20%20%20%20/*%20ncycle%20*/%0Acase%20OP_OpenEphemeral%3A%20%7B%20%20%20%20%20/*%20ncycle%20*/)
> 
> The reason you are hitting this is because as you add larger offsets to your `LIMIT` , more data has to be kept in memory to be sorted until memory limits are hit and disk is used instead.
> 
> Once I have a reproducer I'll let you know of a workaround.

Thank you very much ^^

**Comment by abdelouahabb** [comment] 2024-01-06 13:08
Reproduced it with the code :


```
import apsw
import uuid
import time

def obfuscate(data):
    if not data: return data
    return bytes([x ^ 0xcc for x in data])

class ObfuscatedVFS(apsw.VFS):

    def __init__(self, vfsname="obfuscated", basevfs=""):
        self.vfs_name = vfsname
        self.base_vfs = basevfs
        apsw.VFS.__init__(self, self.vfs_name, self.base_vfs)

    def xOpen(self, name, flags: int):
        return ObfuscatedVFSFile(self.base_vfs, name, flags)


class ObfuscatedVFSFile(apsw.VFSFile):

    def __init__(self, inheritfromvfsname, filename, flags):
        apsw.VFSFile.__init__(self, inheritfromvfsname, filename, flags)

    def xRead(self, amount, offset):
        return obfuscate(super().xRead(amount, offset))

    def xWrite(self, data, offset):
        super().xWrite(obfuscate(data), offset)

obfuvfs = ObfuscatedVFS()

open_flags = apsw.SQLITE_OPEN_READWRITE | apsw.SQLITE_OPEN_CREATE
open_flags |= apsw.SQLITE_OPEN_URI


conn = apsw.Connection("my.db", vfs=obfuvfs.vfs_name)


cur = conn.cursor()

cur.execute('''
            CREATE TABLE IF NOT EXISTS "hello" (
                "a"	CLOB NOT NULL,
                "b"	CLOB NOT NULL,
                "c"	CLOB NOT NULL,
                "d"	CLOB NOT NULL,
                "e" CLOB NOT NULL
            )''')


with conn:
    for i in range(100000):
        cur.execute('''
        insert into hello (`a`, `b`, `c`, `d`, `e`) VALUES (?, ?, ?, ?, ?)
        ''', (str(uuid.uuid4()), str(uuid.uuid4()), str(uuid.uuid4()), str(uuid.uuid4()), str(uuid.uuid4())))


for i in range(9000):
    print("from {0} to {1}".format( i*500, i*500+500) )
    cur.execute("select * from hello order by a limit ?, ?", (i*500, (i*500+500)))
    print(cur.fetchall())
    time.sleep(1)
```

**Comment by rogerbinns** [comment] 2024-01-06 13:58
I was unable to find a workaround such as increasing the cache size.  I am about to commit the fix.  It will be part of the next release [which is soon](https://sqlite.org/forum/forumpost/0aba1473bc).

**Closed** 2024-01-06 13:59 UTC

**Comment by abdelouahabb** [comment] 2024-01-06 15:24
It worked now, performance is a hit (takes more time after that limitation, but at least it works ! )
Here is the result on Linux

![2024-01-06_16-21](https://github.com/rogerbinns/apsw/assets/2527234/6d0a9e29-aa75-401a-9d1f-be7024e57a66)

**Comment by abdelouahabb** [comment] 2024-01-06 15:33
I measured performances with this :

```
for i in range(90):
    try:
        t1 = time.time()
        print("from {0} to {1}".format( i*500, i*500+500) )
        cur.execute("select * from hello order by a limit ?, ?", (i*500, (i*500+500)))
        # print(cur.fetchall())
        print("reached {} characters".format((i+1)*500*36*5))
        perfor.append(time.time() - t1)
        print("performance is {}".format(perfor))
        time.sleep(1)
    except Exception as exc:
        print_augmented_traceback(*sys.exc_info())
        break

```

And it seems it's getting bigger and bigger !

![2024-01-06_16-33](https://github.com/rogerbinns/apsw/assets/2527234/e18703a7-c6c2-4447-9a6f-240563d77c38)

**Comment by rogerbinns** [comment] 2024-01-06 16:38
You are measuring one thing:

> select * from hello order by a limit ?, ?

To do the `order by` SQLite has to do a sort.  The sort time is proportional to the number and size of items being sorted as you have found.

[Turn on logging](https://rogerbinns.github.io/apsw/ext.html#apsw.ext.log_sqlite) and SQLite will tell you if it is creating an automatic index.

Use [EXPLAIN QUERY PLAN](https://www.sqlite.org/eqp.html) to see how SQLite executes your query.  There is [good documentation](https://www.sqlite.org/queryplanner.html) on the principles behind query execution.

You can do this to get a shell in the right place that knows how to format the query plan:

    apsw.shell.Shell(db=conn).process_sql("explain query plan select * from hello order by a limit ?, ?", (i*500, (i*500+500)))

With your code above I get this query plan:

````
  id  parent  detail
   9       0  SCAN hello
  24       0  USE TEMP B-TREE FOR ORDER BY
````

`SCAN` means it is going through the whole table start to finish.  The `TEMP B-TREE` is SQLite having to sort everything on demand.

I did this:

    create index hello_a on hello(a)

Then the query plan becomes:

````
  id  parent  detail
  10       0  SCAN hello USING INDEX hello_a
````

It is instant because SQLite just has to seek to the right location in the index to produce the results and doesn't need to do a sort.

You also don't need that separate cursor and it isn't doing anything for you other than providing a potential source of bugs in the future when you use it while using it.  All the `cur.execute` can and should be replaced with `conn.execute`.

**Comment by abdelouahabb** [comment] 2024-01-06 19:14
> You are measuring one thing:
> 
> > select * from hello order by a limit ?, ?
> 
> To do the `order by` SQLite has to do a sort. The sort time is proportional to the number and size of items being sorted as you have found.
> 
> [Turn on logging](https://rogerbinns.github.io/apsw/ext.html#apsw.ext.log_sqlite) and SQLite will tell you if it is creating an automatic index.
> 
> Use [EXPLAIN QUERY PLAN](https://www.sqlite.org/eqp.html) to see how SQLite executes your query. There is [good documentation](https://www.sqlite.org/queryplanner.html) on the principles behind query execution.
> 
> You can do this to get a shell in the right place that knows how to format the query plan:
> 
> ```
> apsw.shell.Shell(db=conn).process_sql("explain query plan select * from hello order by a limit ?, ?", (i*500, (i*500+500)))
> ```
> 
> With your code above I get this query plan:
> 
> ```
>   id  parent  detail
>    9       0  SCAN hello
>   24       0  USE TEMP B-TREE FOR ORDER BY
> ```
> 
> `SCAN` means it is going through the whole table start to finish. The `TEMP B-TREE` is SQLite having to sort everything on demand.
> 
> I did this:
> 
> ```
> create index hello_a on hello(a)
> ```
> 
> Then the query plan becomes:
> 
> ```
>   id  parent  detail
>   10       0  SCAN hello USING INDEX hello_a
> ```
> 
> It is instant because SQLite just has to seek to the right location in the index to produce the results and doesn't need to do a sort.
> 
> You also don't need that separate cursor and it isn't doing anything for you other than providing a potential source of bugs in the future when you use it while using it. All the `cur.execute` can and should be replaced with `conn.execute`.

Wow ! this just amazing !
Indexing the ordering reduced not only the execute time, but even the bug disapeared without the patch, the patch will improve even better !
Thank you so much !
